#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$(dirname "$0")/common/functions"

exec "$@ *****start*****"
while read log ; do
  exec "$@ $log"
done
exec "$@ *****end*****"