#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$(dirname "$0")/common/functions"

while read log ; do
  if [ "$DK_BASHPID" = "$DK_PPID" ]; then
    exec "$@ $log"
  fi
done