#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$(dirname "$0")/common/functions"

exec "$@ *****start*****"
while read log ; do
  exec "$@ $(echo $(echo "$log" | sed 's/.*[\x01-\x1F\x7F]\[1G//g' | sed "s/'/\"/g"))"
done
exec "$@ *****end*****"