#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$(dirname "$0")/functions"

UUID=$(uuidgen)

VARS="var parameters='$@ $UUID *****start*****'"
exec "$VARS" "${0##*/}"

while read logline ; do
  VARS="var parameters='$@ $UUID $logline'"
  exec "$VARS" "${0##*/}"
done

VARS="var parameters='$@ $UUID *****end*****'"
exec "$VARS" "${0##*/}"